### ISSUE TITLE
How can I do convert WorldExpo'10 datasets' 'roi.mat' to 'mask.mat'?

### ISSUE THREAD

**Issue by guoswang** [diptodip/counting#2]
I am a new student for the research about crowd counting. Now I'm in trouble in the WorldExpo'10 datasets' 'roi.mat'. I don't not how to use it to make it's mask. Can you help me? Thanks a lot!

**Comment by diptodip** [comment]
I don't have access to the original download right now, but in my files there are separate mask files for each of the datasets (not one single ``roi.mat``).

I don't remember if I generated these files myself or if they were in the original dataset. I have a separate folder for each of the scenes with a ``.png`` file inside that is the mask image. Either way, to go from a list of vertices to a mask image, you can use the MATLAB command [``poly2mask``](https://www.mathworks.com/help/images/ref/poly2mask.html). Then you can save the result as an image.

Does this answer your question?

**Comment by guoswang** [comment]
That's helpful. Thanks a lot!
