### ISSUE TITLE
Questions about training WorldExpo‘10 datasets

### ISSUE THREAD

**Issue by guoswang** [diptodip/counting#3]
Hi,

Can you tell me the detials about training  WorldExpo'10?  Only train one model for 5 scenes testing data?
Looking forward to your reply.

Thanks a lot!

**Comment by diptodip** [comment]
That's correct -- both the training and testing data contain a mix of scenes. You can look at the performance of the trained model on testing data from specific scenes, but ultimately the final average of all the scenes is the number worth comparing.

**Comment by guoswang** [comment]
I see. Thanks a lot!
