### ISSUE TITLE
Run train_model.py error

### ISSUE THREAD

**Issue by zengxin1020** [diptodip/counting#6]
Hello, @diptodip 

Thank you for sharing such beautiful work.

When I run train_models.py on UCF-50 datesets, it occurs 
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [1,380,380,1] vs. [1,256,256,1]

I cannot solve it. Can you give me some advices?

**Comment by diptodip** [comment]
Hello,

If that is occurring in training it looks like the label density map and the input image aren't the same shape (which they should be unless you are running with the baseline model). I noticed that I had an old setting for padding in ``patch_extractor.py`` for UCF. I've now set that to be ``0`` by default. Try extracting out patches again and see if that fixes it. Hope this helps!

**Comment by 13052** [comment]
yes, set the pad = 0 in `patch_extractor.py`  can solve this problem, I have encountered this problem.

**Comment by wwwzxoe303com** [comment]
> Hello,
> 
> If that is occurring in training it looks like the label density map and the input image aren't the same shape (which they should be unless you are running with the baseline model). I noticed that I had an old setting for padding in `patch_extractor.py` for UCF. I've now set that to be `0` by default. Try extracting out patches again and see if that fixes it. Hope this helps!

Thank you point it out!

**Comment by zengxin1020** [comment]
@diptodip Thank you point it out!

**Comment by zengxin1020** [comment]
@13052 Thanks!
